# -*- coding: utf-8 -*-
"""Pelin_Kiliboz_MIDTERM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JUCc3QqN7gKLHiVQXMVALq1RzQTMvjdI

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on 
Drive.
ex: atay_ilgun_MIDTERM.ipynb

Also, create all TD related tasks on one TD file and upload it.
ex: atay_ilgun_MIDTERM.tox
"""



"""Describe what an algorithm is."""

# An algorithm is a set of rules and calculations that solves a problem and gives out a result according to the information fed into it. It could be viewed as a recipe that you can change slightly and get different variations of the same type of result.

"""Explain in what ways algorithmic design is different than the brute-force regular design approach. [50 words]"""

# In the regular design approach and idea is formed and visualised solely by the designer. But algorithmic design means that the designer has an idea, sets the intention for the project, feeds the necessary information to algorithms that are designed to solve problems according to the intention and lets the algorithms provide the optimal solutions and variations to reach the desired purpose.

"""In 100 words meditate on how an new approach on design such as one that is algorithmic could affect your work practice."""

# In a time where algorithms and machines are evolving greatly and at an extremely high pace, transforming the way we work, live and think; it is crucial for art and design to also adapt and collaborate with these developments. Though we already depend on software to solve most of our design problems, being able to create your own tools and getting help from them means that you open the doors to a much more limitless realm where your workflow can be vastly improved and accelerated, ideas are free from restriction and creativity can blossom. Thus I believe it is a way to create much more functional and powerful art.

"""Create a python dictionary for your name surname and year of birth."""

dict_pelin = {'name': 'pelin', 'surname': 'kiliboz', 'year': '1994'}

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

if dict_pelin['name'][0] == 'a':
  print('my initial is a!')

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

if len(dict_pelin['surname'])%3:
  print('it is divisible')
else:
  print('not divisible')

"""Change your year of birth to 2678."""

dict_pelin[3] = 2678

"""TOUCHDESIGNER TIME.

Create a red box [in geo comp] and make it emit particles with a birth rate of 2500.
"""





"""Import a moving image and a sound file in TD.
Add at least two filters to the image file.
Make 2 parameters of these filters responsive to the audio.
"""



"""Create a torus and modify its x-size with an LFO with the frequency of 0.75."""



"""Create a sphere and create an amorph moving shape using 'noise'."""



"""Create a box and apply an image texture on it."""